name: example
on: [push]
jobs:
 commit:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@c7d749a2d57b4b375d1ebcd17cfbfb60c676f18e
     - shell: bash
       run: |
         echo 'hello world!'

